// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpURBb4fPDEVJ5om7CK7LaHjDUSOL7dpE',
    appId: '1:436823356091:web:406b901367e080001c6f9e',
    messagingSenderId: '436823356091',
    projectId: 'aura-d3e5f',
    authDomain: 'aura-d3e5f.firebaseapp.com',
    databaseURL: 'https://aura-d3e5f-default-rtdb.firebaseio.com',
    storageBucket: 'aura-d3e5f.firebasestorage.app',
    measurementId: 'G-GGSMJGF5PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY0gw63NwnFu16tt90-qQ4MP8tMYqcsik',
    appId: '1:436823356091:android:251f4f0bb92971b61c6f9e',
    messagingSenderId: '436823356091',
    projectId: 'aura-d3e5f',
    databaseURL: 'https://aura-d3e5f-default-rtdb.firebaseio.com',
    storageBucket: 'aura-d3e5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_i4eA8b_wrVe3aSpjic6N8bKAZvQVb9o',
    appId: '1:436823356091:ios:fde3a23ee15d525a1c6f9e',
    messagingSenderId: '436823356091',
    projectId: 'aura-d3e5f',
    databaseURL: 'https://aura-d3e5f-default-rtdb.firebaseio.com',
    storageBucket: 'aura-d3e5f.firebasestorage.app',
    iosClientId: '436823356091-tc1i1j40vlih3jhlvt448ceolbqed2bo.apps.googleusercontent.com',
    iosBundleId: 'com.example.aurapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_i4eA8b_wrVe3aSpjic6N8bKAZvQVb9o',
    appId: '1:436823356091:ios:fde3a23ee15d525a1c6f9e',
    messagingSenderId: '436823356091',
    projectId: 'aura-d3e5f',
    databaseURL: 'https://aura-d3e5f-default-rtdb.firebaseio.com',
    storageBucket: 'aura-d3e5f.firebasestorage.app',
    iosClientId: '436823356091-tc1i1j40vlih3jhlvt448ceolbqed2bo.apps.googleusercontent.com',
    iosBundleId: 'com.example.aurapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpURBb4fPDEVJ5om7CK7LaHjDUSOL7dpE',
    appId: '1:436823356091:web:91ab08be104ffc101c6f9e',
    messagingSenderId: '436823356091',
    projectId: 'aura-d3e5f',
    authDomain: 'aura-d3e5f.firebaseapp.com',
    databaseURL: 'https://aura-d3e5f-default-rtdb.firebaseio.com',
    storageBucket: 'aura-d3e5f.firebasestorage.app',
    measurementId: 'G-0LPL1S534T',
  );
}
